routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::get('/', 'Web\PageController@home');
Route::get('/login', 'Auth\LoginController@index');
Route::get('/register', 'Auth\RegisterController@index');
Route::get('getSubServices/{id}','Auth\RegisterController@getSubServices');
Route::get('admin-login', 'Auth\LoginController@adminLoginView');



Route::get('email','Web\PageController@email');
Route::get('/home', 'Web\PageController@home');
Route::get('/services', 'Web\PageController@services');
Route::get('/services/{slug}', 'Web\PageController@services');
//Route::get('/service/{slug}', 'Web\PageController@serviceDetail');

Route::get('/rate-list', 'Web\PageController@rateList');
Route::get('/about-us', 'Web\PageController@aboutUs');
Route::get('/terms', 'Web\PageController@terms');
Route::get('/portfolio', 'Web\PageController@portfolio');
Route::get('/order-now', 'Web\PageController@orderNow');
Route::get('getSubServices/{id}', 'Web\PageController@getSubServices');
Route::get('getSubServices/{id}', 'Web\UserController@getSubServices');


Route::get('change-status/{id}','Web\OrderController@changeStatus');
Route::get('check-otp-valid', 'OtpController@checkOtpValid')->name('checkOtpValid');
Route::get('resend-otp', 'OtpController@reSendOtp');
Route::get('check-user-password-valid', 'Web\UserController@checkUserPasswordValid')->name('checkUserPasswordValid');
Route::get('forgot-password', 'Web\UserController@forgotPassword')->name('forgotPassword');

Route::post('instance-order', 'Web\OrderController@instanceOrder')->name('instanceOrder');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('admin-login', 'Auth\LoginController@adminLogin')->name('adminLogin');
Route::post('register', 'Auth\RegisterController@register')->name('register');
Route::resource('quote','Web\QuoteController');
ROute::post('quoteSave','Web\QuoteController@store')->name('quoteSave');
Route::get('email/{id}','Web\PageController@email');


Route::prefix('admin')->middleware(['auth','Admin'])->group(function () {
    Route::resource('services','Admin\ServiceController');
    Route::resource('staffs','Admin\StaffController');
    Route::resource('users','Admin\UserController');
    Route::resource('orders','Admin\OrderController');
    Route::resource('areas','Admin\AreaController');
    Route::resource('dashboard','Admin\DashboardController');

    Route::resource('subServices','Admin\SubServiceController');
    Route::resource('trendingService','Admin\TrendingServiceController');
    Route::resource('quotes','Admin\QuoteController');
    Route::resource('Facebook','Admin\FacebookController');
    Route::get('pdfDownload/{id}','Admin\OrderController@pdfDownload')->name('pdfDownload');
    Route::get('get-Sub-Services/{id}','Admin\StaffController@getSubServices');
    Route::get('printView/{id}','Admin\OrderController@printView')->name('printView');
    Route::get('assign/{id}','Admin\OrderController@assign')->name('assign');
    Route::post('assignOrder/{id}','Admin\OrderController@assignOrder')->name('assignOrder');

    Route::resource('invoices','Admin\InvoiceController');
    Route::get('print/{id}','Admin\InvoiceController@printView')->name('print');

    Route::resource('galleries', 'Admin\GalleryController');
    Route::resource('categories', 'Admin\CategoriesController');
    Route::resource('sub_categories', 'Admin\SubCategoryController');
    Route::get('sub_categorie/{id}', 'Admin\SubCategoryController@getCats');

    Route::get('index','Admin\OrderController@index')->name('home');
    Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
    Route::get('order-detail/{id}','Admin\OrderController@orderDetail');
    Route::get('staff-detail/{id}','Admin\StaffController@staffDetail');
    Route::post('change-status','Admin\OrderController@changeStatus');
    Route::post('order-update/{id}','Admin\OrderController@orderUpdate');
    Route::get('invoice-detail/{id}','Admin\OrderController@invoice');
    Route::get('pdfView/{id}','Admin\OrderController@pdfView')->name('pdfView');
    Route::get('printView/{id}','Admin\OrderController@printView')->name('printView');
    Route::get('userChart','Admin\DashboardController@userChart')->name('userChart');




//    Route::get('pdfDownload/{id}','Admin\InvoiceController@pdf')->name('pdfDownload');


});

Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
Route::post('password/email', 'Auth\ResetPasswordController@sendResetLink')->name('password.email');
//Route::get('password/email', 'Auth\ResetPasswordController@sendResetLink')->name('password.email');



Route::middleware(['auth'])->group(function () {
    Route::resource('order','Web\OrderController');
    Route::resource('user','Web\UserController');
    Route::post('update-user-info','Web\UserController@update')->name('setUserPassword');
    Route::post('update-profile','Web\UserController@updateProfile')->name('updateProfile');
    Route::get('logout', 'Auth\LoginController@logout');
    Route::get('/profile','Web\UserController@index');
    Route::get('order-detail/{id}','Web\OrderController@orderDetail');
    Route::post('addMobile/{id}','Web\OrderController@addMobile')->name('addMobile');
    Route::post('addNote/{id}','Web\OrderController@addNote')->name('addNote');
    Route::post('addAddress/{id}','Web\OrderController@addAddress')->name('addAddress');
    Route::post('addTimeSlot/{id}','Web\OrderController@addTImeSlot')->name('addTimeSlot');
    Route::delete('deleteImage/{id}','Web\UserController@deleteImage')->name('deleteImage');
    Route::get('staffOrder','Web\UserController@staffOrder')->name('staffOrder');
    Route::get('viewStaff/{id}','Web\UserController@viewStaff')->name('viewStaff');
    Route::get('rating/{id}','Web\OrderController@rating')->name('rating');
    Route::post('ratingSubmit/{id}','Web\OrderController@ratingSubmit')->name('ratingSubmit');
    Route::post('changeStatusOrder/{id}','Web\OrderController@changeStatusOrder')->name('changeStatusOrder');
});

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Facebook;
use App\Order;
use App\Staff;
use App\Status;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user =User::all();
        $user1 = User::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-7 days')) );
        $user_today = User::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-1 days')) );
        $user1 = User::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-7 days')) );
        $staff_week = Staff::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-7 days')));
        $staff_today = Staff::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-1 days')) );
        $staff = Staff::all();
        $order_week = Order::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-7 days')) );
        $order_today = Order::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-1 days')) );
        $order = Order::all();
        return view('dashboard.MainDashboard.v1',compact('user','user_today','order','user1','order_week','order_today','staff_week','staff_today','staff'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

    }
    public function userChart(Request $request, $id = null)
    {
        $staff = Staff::selectRaw('year(created_at) year, monthname(created_at) month, count(*) data')
            ->groupBy('year', 'month')
            ->orderBy('year', 'asc')
            ->get();

        if(count($staff) > 0){
            foreach ($staff as $k => $result) {
                $staff1[$k]['value']  = (int)$result->data;
                $staff1[$k]['month'] = $result->month;
            }

        }else{
            $staff1 = [];
        }

        $staff = $staff1;
//        dd($staff);
        $social_users= User::selectRaw('year(created_at) year, monthname(created_at) month, count(*) data')
            ->groupBy('year', 'month')
            ->orderBy('year', 'asc')
            ->get();
//        dd($social_users);
        if(count($social_users) > 0){
            foreach ($social_users as $k => $result) {
                $social_users1[$k]['value']  = (int)$result->data;
                $social_users1[$k]['month'] = $result->month;
            }

        }else{
            $social_users1 = [];
        }

        $social_users = $social_users1;
//        dd( $social_users1[$k]['month']);
        $order = Order::selectRaw('year(created_at) year, monthname(created_at) month, count(*) data')
            ->groupBy('year', 'month')
            ->orderBy('year', 'asc')
            ->get();

        if(count($order) > 0){
            foreach ($order as $k => $result) {
                $order1[$k]['value']  = (int)$result->data;
                $order1[$k]['month'] = $result->month;
            }

        }else{
            $order1 = [];
        }

        $order = $order1;
//        facebook data chart
        $facebook = Facebook::selectRaw('year(created_at) year, monthname(created_at) month, count(*) data')
            ->groupBy('year', 'month')
            ->orderBy('year', 'asc')
            ->get();
        if(count($facebook) > 0){
            foreach ($facebook as $k => $result) {
                $facebook1[$k]['value']  = (int)$result->data;
                $facebook1[$k]['month'] = $result->month;
            }

        }else{
            $facebook1 = [];
        }
        $facebook = $facebook1;

//       $status= $order_status ->whereStatus('pending')->first();
//        dd($status->status->toArray());
        $status =Order::where('status_id',3)->count();
//        dd($status );
        if($status){
            $order_price = Order::selectRaw('year(created_at) year, monthname(created_at) month, sum(order_price) as sum')
                ->groupBy('year', 'month')
                ->orderBy('year', 'asc')
                ->get();
//           dd($order_price);
            if(count($order_price) > 0){
                foreach ($order_price as $k => $result) {
                    $order_price1[$k]['value']  = (int)$result->sum;
                    $order_price1[$k]['month'] = $result->month;
                }

            }else{
                $order_price1 = [];
            }

            $order_price = $order_price1;
        }else{
            return back();
        }

        return view('dashboard.MainDashboard.user-chart',compact('social_users','staff','order','facebook','order_price'))
           ;

    }


}

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Gallery;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lists = Gallery::with('sub_category')->get();
        $data = Category::all();

        return view('dashboard.gallery.list',compact('lists','data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.gallery.insert');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request,[
            'alt'=>'required|string|max:30',
            'image' => 'required|file|image|mimes:jpeg,png,gif,webp|max:2048'
        ]);

        $input = $request->all();
        $input['slug'] = makeSlug($input['name'], new Gallery());
        //Multi Images
        $images = [];
        if($files=$request->file('images')){
            foreach($files as $k => $file){
                $name = time() .$k. '.' . $file->getClientOriginalExtension();
                $file->move('assets/uploads',$name);
                $images[$k] = $name;
            }
            $input['images'] = implode(',',$images);

        }

        $input['image'] = imageUpload_gallery($request, 'assets/uploads');
        Gallery::create($input);
        $lists = Gallery::with('sub_category')->get();
       if (!is_null($lists)){
           toastr()->success('Image added Successfully!');
       }else{
           toastr()->error('Something went wrong');
       }
        return view('dashboard.gallery.list',compact('lists'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Gallery::findorfail($id);
//         dd($post->sub_category->category);
        return view('dashboard.gallery.edit',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function edit(Gallery $gallery)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request ,$id)
    {
        $input = $request->all();
        $input['slug'] = makeSlug($input['name'], new Gallery());
        if(!$request->image){
            $input['image'] = $request->old_image;
        }else{
            $input['image'] = imageUpload_gallery($request, 'assets/uploads', 'assets/uploads/'.$request->old_image);

        }
//        image update but old image not delete
        if (!$request->edit_images){
            if ($request->images){
                if($files=$request->file('images')){
                    foreach($files as $k => $file){
                        $name = time() .$k. '.' . $file->getClientOriginalExtension();
                        $file->move('assets/uploads',$name);
                        $images[$k] = $name;
                    }
                    $input['images'] = implode(',',$images).','.$request->old_images;
                }

            }
        }else{
            if (isset($request->images)){
                if($files=$request->file('images')){
                    foreach($files as $k => $file){
                        $name = time() .$k. '.' . $file->getClientOriginalExtension();
                        $file->move('assets/uploads',$name);
                        $images[$k] = $name;
                    }
                    $input['images'] = implode(',',$images). ',' .$request->edit_images;
                    $input['images'] = substr_replace($input['images'], "", -1);

                }
//                $input['images'] += $input['edit_images'];
            }else{//if new_images->Has but not any new Images
                $input['images'] = $input['edit_images'];
                $input['images'] = substr_replace($input['images'], "", -1);
            }
        }
//        dd($input['images']);
        Gallery::findorfail($id)->update($input);

        $lists = Gallery::with('sub_category')->get();
        if (!is_null($lists)){
            toastr()->success('Images updated Successfully!');
        }else{
            toastr()->error('SomeThing went wrong!');
        }

        return view('dashboard.gallery.list',compact('lists'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $gallery= Gallery::destroy($id);
        if (!is_null($gallery)){
            toastr()->success('Image Deleted Successfully!');
        }else{
            toastr()->error('SomeThing went Wrong');
        }
        return redirect()->back();
    }


}

resources/views/dashboard/gallery/insert.blade.php
{{-- Extends Layout --}}
@extends('layouts.master')

@section('content')
    <style>
        textarea {
            overflow: auto;
            resize: none !important;
            width: 100%;
        }
        .modal-footer{
            text-align: center !important;
            display: block !important;
        }
        .form-control{
            padding: 0px !important;
            height: 33px !important;
        }
        .chosen-default, .chosen-single{
            height: 33px !important;
            padding-top: 5px !important;
        }
        .text{
            font-weight: 600;
        }
        .modal-title{
            font-weight: bold !important;
            margin:0 auto !important;
            font-size: 30px !important;
        }
        .btn-success{
            padding: 5px 35px !important;
            background: #0f3e7c !important;
            color: white !important;
            border: none !important;
        }

        .table-responsive .modal-header{
            background: #0f3e7c !important;
            color: white !important;
        }
    </style>
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
    <div style="background-color: #fff;margin: -39px 0;">
        <div class="row">
            <div class="col-md-4">
            </div>
        </div>
        <br>
        <div class="table-responsive list-records">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Insert Data</h4>
                </div>
                <div class="model-body">
                    <form action="{{ route('galleries.store')}}" method="POST" id="form-data" enctype="multipart/form-data" >
                        @csrf
                        <div class="modal-body">
                     <div class="row">
                         <div class="col-md-6">
                             <div class="text">
                            Category :<select name="category" id="category" class="form-control">
                                <option>Select</option>
                                @foreach(App\Category::all() as $options)
                                    <option value="{{ $options->id }}">{{ $options->name }}</option>
                                @endforeach
                                    </select>
                             </div>
                         </div>
                         <div class="col-md-6">
                             <div class="text">
                            Subcategory :<select name="subCategory_id" id="subcategory" class="form-control"></select>
                             </div>
                         </div>
                     </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="text" style="padding: 16px 0;">
                                    Images :<input required type="file" class="form-control" name="images[]" placeholder="address" multiple>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="text" style="padding: 16px 0;">
                            Post :<input type="file" name="image" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                    <div class="col-md-3">
                                    <div class="text">
                                        Title :<input type="text" name="name" class="form-control">
                                    </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="text">
                                            Banner-Number :<input type="number" name="sort" class="form-control">
                                        </div>
                                    </div>

                                <div class="col-md-6">
                                    <div class="form-group" style="margin-top: -8px;">
                                        <label for="usr">Meta keywords:</label>
                                        <input type="text" class="form-control" id="meta_keywords" name="meta_keywords" />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                            <div class="col-md-6">
                            <div class="form-group">
                                <label for="usr">Meta Title:</label>
                                <input type="text" class="form-control" id="meta_title" name="meta_title" />
                            </div>
                            </div>

                            <div class="col-md-6">
                            <div class="form-group">
                                <label for="usr">Meta Description:</label>
                                <input type="text" class="form-control" id="meta_description" name="meta_description" />
                            </div>
                            </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                <div class="form-group">
                                    <label for="usr">URL:</label>
                                    <input type="text" class="form-control" id="url" name="url" />
                                </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="usr">ALT:</label>
                                        <input type="text" class="form-control" id="alt" name="alt" required/>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="text" style="padding: 9px 0;">
                                        Description :<textarea type="text" class="form-control" id="textarea"  name="description"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input type="submit" class="btn btn-success" value="Insert">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
        </div>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        $(document).ready(function(){
            $('select[name="category"]').change(function (e) {
                var cat_id = $(this).val();
                //Ajax
                $.ajax({
                    url : "{{ url('admin/sub_categorie') }}/"+cat_id,
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                    success:function (result) {
                        $('select[name="subCategory_id"]').empty();
                        $.each(result.data, function (i, value) {
                            $('select[name="subCategory_id"]').append('<option value="'+ value.id+'">'+value.name+'</option>');
                        });
                        $('select[name="subCategory_id"]').trigger("chosen:updated");
                    }

                });
            });
        });
    </script>
@endsection

resources/views/dashboard/gallery/list.blade.php
{{-- Extends Layout --}}
@extends('layouts.master')

@section('content')
    <style>
        .table thead{
            background: #0f3e7c !important;
            color: white !important;
        }
        th {
            white-space: nowrap;
        }
        .btn-info{
            background: #0f3e7c;
        }
        .btn-info:hover{
            background: #ce171f !important;
            color: #fff;
            border-color: #ce171f !important;
        }
    </style>

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <a href="{{ route('galleries.create') }}" type="button" class="btn btn-info btn-lg">Add New</a>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{url('admin/dashboard')}}">Home</a></li>
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol>
                    </div>
                </div>
            </div>
<div style="background-color: #fff; padding: 15px 15px 0">
    <div class="row">
        <div class="col-md-4">
        </div>
    </div>
    <br>
    <div class="table-responsive list-records">
        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th>#</th>
                <th scope="col">Image</th>
                <th scope="col">Images</th>
                <th scope="col" style="padding-right: 117px;">Sub Category | Category</th>
                <th scope="col">Name</th>
                <th scope="col">Image Number</th>
                <th scope="col">Description</th>
                <th scope="col">Meta Title</th>
                <th scope="col">Meta Description</th>
                <th scope="col">Links</th>
                <th scope="col">ALT</th>
                <th scope="col">Meta keywords</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
             <?php
                $x=1
             ?>
            @foreach($lists as $list)

                <tr>
                    <td>{{ $x++ }}</td>
                    <td><img alt="" src="{{asset('assets/uploads')}}{{ '/'.$list->image }}" style="width: 70px;height: 70px"></td>

                    @if($list->images)
                        @php
                            $list->images = explode(',',$list->images);
                        @endphp
                        <td>
                            @foreach($list->images as $image)
                                 <img alt="" src="{{asset('assets/uploads')}}{{ '/'.$image }}" width="30px" height="30px">
                            @endforeach
                        </td>
                    @endif

                    <td>
                        {{  !is_null($list->sub_category) ? $list->sub_category->name : ''}} | {{  !is_null($list->sub_category) && !is_null($list->sub_category->category) ? $list->sub_category->category->name : ''}}
                    </td>
                    <td>{{ $list->name }}</td>
                    <td>{{$list->sort}}</td>
                    <td>{!! \Illuminate\Support\Str::words($list->description, $words = 25, $end = '...') !!}</td>
                    <td>{{ $list->meta_title }}</td>
                    <td>{{ $list->meta_description }}</td>
                    <td>{{$list->url}}</td>
                    <td>{{$list->ALT}}</td>
                    <td>{{ $list->meta_keywords }}</td>
                    <td>
                        <div class="btn-group">
                            <form action="{{ route('galleries.show',$list->id) }}" method="get">
                                <input style="padding: 4px 20px;" type="submit" class="btn btn-primary btn-sm" value="Edit" ></input>
                            </form>
                            <form id="formDeleteModel_1" action="{{ route('galleries.destroy',$list->id) }}" method="POST" class="form-inline">
                                @csrf
                                {{ method_field('DELETE') }}
                                <input type="submit" class="btn btn-danger btn-sm" value="Delete"></input>
                            </form>
                        </div>
                        <!-- Delete Record Form -->
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
    </div>
</div>

        </div>
    </div>


@endsection

@section('footer-extras')

    <script type="application/javascript">
        //Tiny Editor----Start

        $(document).ready(function(){
            $('#textarea').summernote();
        });
        //Tiny Editor----End
        //----Show Sub Category
        $('#category').on('change',function (e) {
            var cat_id = e.target.value;
            //Ajax
            $.ajax({
                url : "{{ url('admin/subCat') }}/"+cat_id,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                success:function (result) {
                    $('#subcategory').empty();
                    $.each(result.data, function (index, SubcatObj) {
//                        alert(SubcatObj.categories_id);
                        if(SubcatObj.category_id == cat_id)
                        {
                            $('#subcategory').append('<option value="'+ SubcatObj.id+'">'+SubcatObj.name+'</option>');
                        }
                    });
                }
            });
        });
    </script>
@endsection