routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::get('/', 'Web\PageController@home');
Route::get('/login', 'Auth\LoginController@index');
Route::get('/register', 'Auth\RegisterController@index');
Route::get('getSubServices/{id}','Auth\RegisterController@getSubServices');
Route::get('admin-login', 'Auth\LoginController@adminLoginView');



Route::get('email','Web\PageController@email');
Route::get('/home', 'Web\PageController@home');
Route::get('/services', 'Web\PageController@services');
Route::get('/services/{slug}', 'Web\PageController@services');
//Route::get('/service/{slug}', 'Web\PageController@serviceDetail');

Route::get('/rate-list', 'Web\PageController@rateList');
Route::get('/about-us', 'Web\PageController@aboutUs');
Route::get('/terms', 'Web\PageController@terms');
Route::get('/portfolio', 'Web\PageController@portfolio');
Route::get('/order-now', 'Web\PageController@orderNow');
Route::get('getSubServices/{id}', 'Web\PageController@getSubServices');
Route::get('getSubServices/{id}', 'Web\UserController@getSubServices');


Route::get('change-status/{id}','Web\OrderController@changeStatus');
Route::get('check-otp-valid', 'OtpController@checkOtpValid')->name('checkOtpValid');
Route::get('resend-otp', 'OtpController@reSendOtp');
Route::get('check-user-password-valid', 'Web\UserController@checkUserPasswordValid')->name('checkUserPasswordValid');
Route::get('forgot-password', 'Web\UserController@forgotPassword')->name('forgotPassword');

Route::post('instance-order', 'Web\OrderController@instanceOrder')->name('instanceOrder');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::post('admin-login', 'Auth\LoginController@adminLogin')->name('adminLogin');
Route::post('register', 'Auth\RegisterController@register')->name('register');
Route::resource('quote','Web\QuoteController');
ROute::post('quoteSave','Web\QuoteController@store')->name('quoteSave');
Route::get('email/{id}','Web\PageController@email');


Route::prefix('admin')->middleware(['auth','Admin'])->group(function () {
    Route::resource('services','Admin\ServiceController');
    Route::resource('staffs','Admin\StaffController');
    Route::resource('users','Admin\UserController');
    Route::resource('orders','Admin\OrderController');
    Route::resource('areas','Admin\AreaController');
    Route::resource('dashboard','Admin\DashboardController');

    Route::resource('subServices','Admin\SubServiceController');
    Route::resource('trendingService','Admin\TrendingServiceController');
    Route::resource('quotes','Admin\QuoteController');
    Route::resource('Facebook','Admin\FacebookController');
    Route::get('pdfDownload/{id}','Admin\OrderController@pdfDownload')->name('pdfDownload');
    Route::get('get-Sub-Services/{id}','Admin\StaffController@getSubServices');
    Route::get('printView/{id}','Admin\OrderController@printView')->name('printView');
    Route::get('assign/{id}','Admin\OrderController@assign')->name('assign');
    Route::post('assignOrder/{id}','Admin\OrderController@assignOrder')->name('assignOrder');

    Route::resource('invoices','Admin\InvoiceController');
    Route::get('print/{id}','Admin\InvoiceController@printView')->name('print');

    Route::resource('galleries', 'Admin\GalleryController');
    Route::resource('categories', 'Admin\CategoriesController');
    Route::resource('sub_categories', 'Admin\SubCategoryController');
    Route::get('sub_categorie/{id}', 'Admin\SubCategoryController@getCats');

    Route::get('index','Admin\OrderController@index')->name('home');
    Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
    Route::get('order-detail/{id}','Admin\OrderController@orderDetail');
    Route::get('staff-detail/{id}','Admin\StaffController@staffDetail');
    Route::post('change-status','Admin\OrderController@changeStatus');
    Route::post('order-update/{id}','Admin\OrderController@orderUpdate');
    Route::get('invoice-detail/{id}','Admin\OrderController@invoice');
    Route::get('pdfView/{id}','Admin\OrderController@pdfView')->name('pdfView');
    Route::get('printView/{id}','Admin\OrderController@printView')->name('printView');
    Route::get('userChart','Admin\DashboardController@userChart')->name('userChart');




//    Route::get('pdfDownload/{id}','Admin\InvoiceController@pdf')->name('pdfDownload');


});

Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
Route::post('password/email', 'Auth\ResetPasswordController@sendResetLink')->name('password.email');
//Route::get('password/email', 'Auth\ResetPasswordController@sendResetLink')->name('password.email');



Route::middleware(['auth'])->group(function () {
    Route::resource('order','Web\OrderController');
    Route::resource('user','Web\UserController');
    Route::post('update-user-info','Web\UserController@update')->name('setUserPassword');
    Route::post('update-profile','Web\UserController@updateProfile')->name('updateProfile');
    Route::get('logout', 'Auth\LoginController@logout');
    Route::get('/profile','Web\UserController@index');
    Route::get('order-detail/{id}','Web\OrderController@orderDetail');
    Route::post('addMobile/{id}','Web\OrderController@addMobile')->name('addMobile');
    Route::post('addNote/{id}','Web\OrderController@addNote')->name('addNote');
    Route::post('addAddress/{id}','Web\OrderController@addAddress')->name('addAddress');
    Route::post('addTimeSlot/{id}','Web\OrderController@addTImeSlot')->name('addTimeSlot');
    Route::delete('deleteImage/{id}','Web\UserController@deleteImage')->name('deleteImage');
    Route::get('staffOrder','Web\UserController@staffOrder')->name('staffOrder');
    Route::get('viewStaff/{id}','Web\UserController@viewStaff')->name('viewStaff');
    Route::get('rating/{id}','Web\OrderController@rating')->name('rating');
    Route::post('ratingSubmit/{id}','Web\OrderController@ratingSubmit')->name('ratingSubmit');
    Route::post('changeStatusOrder/{id}','Web\OrderController@changeStatusOrder')->name('changeStatusOrder');
});

app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
     protected $table ='areas';
     protected $fillable = [
         'name',
     ];
    public function orders()
    {
        return $this->hasMany('App\Order','area_id');
    }
    public function staffs()
    {
        return $this->belongsToMany('App\Staff','area_staff')->withPivot('staff_id','area_id');
    }
    public function service()
    {
        return $this->belongsToMany('App\Service');
    }
}

app/Models/Repositories/Area.php
<?php

namespace App\Models\Repositories;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Area.
 *
 * @package namespace App\Models\Repositories;
 */
class Area extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [];

}

app/Http/Controllers/Admin/AreaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Area;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\areaValid;

use Illuminate\Cache\Repository;
use Illuminate\Http\Request;
use App\Repositories\AreaRepository;
use Mockery\Exception;

class AreaController extends Controller
{
    protected $areaRepository;

    public function __construct(AreaRepository $areaRepository)
    {
        $this->middleware('auth');
        $this->areaRepository = $areaRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->get('search')){

            $area= Area::where('name','like','%'.$request->get('search').'%')->paginate(5);

        }else{
            $area =$this->areaRepository->paginate('9');
        }
        return view('dashboard.Area.index',compact('area'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(areaValid $request)
    {
        $area = $this->areaRepository->create($request->only('name'));
        if ($area){
            toastr()->success('Area  Added Successfully! ');

        }else{
            toastr()->error('Something went Wrong');
        }
        return redirect()->back();


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function edit( $id)
    {
        $area = $this->areaRepository->find($id);
        if ($area){
            toastr()->info('Edit your Area!');

        }else{
            toastr()->warning('Somthinf Went Wrong!');
        }
       return view('dashboard.Area.edit',compact('area'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
         $this->validate($request,[
         'name'=>'nullable|string'
          ]);
        $input = $request->all();
        $update = $this->areaRepository->update($input,$id);
        if ($update){
            toastr()->success('Area Updated Successfully ');
        }else{
            toastr()->error('Something Went Wrong');
        }
        return redirect('admin/areas');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $areas = $this->areaRepository->delete($id);
        if ($areas){
            toastr()->success('Area Deleted Successfully!');
        }else{
            toastr()->error('Something Went Wrong');
        }
        return redirect()->back();
    }
}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Facebook;
use App\Order;
use App\Staff;
use App\Status;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user =User::all();
        $user1 = User::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-7 days')) );
        $user_today = User::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-1 days')) );
        $user1 = User::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-7 days')) );
        $staff_week = Staff::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-7 days')));
        $staff_today = Staff::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-1 days')) );
        $staff = Staff::all();
        $order_week = Order::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-7 days')) );
        $order_today = Order::all()->where('created_at', '>=', date('Y-m-d H:i:s',strtotime('-1 days')) );
        $order = Order::all();
        return view('dashboard.MainDashboard.v1',compact('user','user_today','order','user1','order_week','order_today','staff_week','staff_today','staff'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

    }
    public function userChart(Request $request, $id = null)
    {
        $staff = Staff::selectRaw('year(created_at) year, monthname(created_at) month, count(*) data')
            ->groupBy('year', 'month')
            ->orderBy('year', 'asc')
            ->get();

        if(count($staff) > 0){
            foreach ($staff as $k => $result) {
                $staff1[$k]['value']  = (int)$result->data;
                $staff1[$k]['month'] = $result->month;
            }

        }else{
            $staff1 = [];
        }

        $staff = $staff1;
//        dd($staff);
        $social_users= User::selectRaw('year(created_at) year, monthname(created_at) month, count(*) data')
            ->groupBy('year', 'month')
            ->orderBy('year', 'asc')
            ->get();
//        dd($social_users);
        if(count($social_users) > 0){
            foreach ($social_users as $k => $result) {
                $social_users1[$k]['value']  = (int)$result->data;
                $social_users1[$k]['month'] = $result->month;
            }

        }else{
            $social_users1 = [];
        }

        $social_users = $social_users1;
//        dd( $social_users1[$k]['month']);
        $order = Order::selectRaw('year(created_at) year, monthname(created_at) month, count(*) data')
            ->groupBy('year', 'month')
            ->orderBy('year', 'asc')
            ->get();

        if(count($order) > 0){
            foreach ($order as $k => $result) {
                $order1[$k]['value']  = (int)$result->data;
                $order1[$k]['month'] = $result->month;
            }

        }else{
            $order1 = [];
        }

        $order = $order1;
//        facebook data chart
        $facebook = Facebook::selectRaw('year(created_at) year, monthname(created_at) month, count(*) data')
            ->groupBy('year', 'month')
            ->orderBy('year', 'asc')
            ->get();
        if(count($facebook) > 0){
            foreach ($facebook as $k => $result) {
                $facebook1[$k]['value']  = (int)$result->data;
                $facebook1[$k]['month'] = $result->month;
            }

        }else{
            $facebook1 = [];
        }
        $facebook = $facebook1;

//       $status= $order_status ->whereStatus('pending')->first();
//        dd($status->status->toArray());
        $status =Order::where('status_id',3)->count();
//        dd($status );
        if($status){
            $order_price = Order::selectRaw('year(created_at) year, monthname(created_at) month, sum(order_price) as sum')
                ->groupBy('year', 'month')
                ->orderBy('year', 'asc')
                ->get();
//           dd($order_price);
            if(count($order_price) > 0){
                foreach ($order_price as $k => $result) {
                    $order_price1[$k]['value']  = (int)$result->sum;
                    $order_price1[$k]['month'] = $result->month;
                }

            }else{
                $order_price1 = [];
            }

            $order_price = $order_price1;
        }else{
            return back();
        }

        return view('dashboard.MainDashboard.user-chart',compact('social_users','staff','order','facebook','order_price'))
           ;

    }


}

resources/views/dashboard/Area/edit.blade.php
@extends('layouts.master')
@section('content')
<style>
    #example1 .bg-clr{
        background: #0f3e7c;color: white;
    }
    .area-text{
        font-weight: 600;
        font-size: 30px !important;
    }
    .savings{
        padding: 9px 50px;
        background: #0f3e7c !important;
        color: white !important;
        border: none !important;
    }
</style>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <h1 class="text-center area-text">Area Edit</h1>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel-body">

        </div>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="box-body">
                    <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                            <!-- Submit form with a button -->
                            <tr role="row" class="bg-clr">
                                <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending"
                                    aria-label="Rendering engine: activate to sort column descending" style="width: 213.247px;">Id</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 262.135px;">Name
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 262.135px;">Action
                                </th>
                            </tr>
                            <tbody>
                                <tr role="row" class="odd">
                                    <form action="{{route('areas.update',$area->id)}}" method="post">
                                        @csrf
                                        @method('PUT')
                                    <td class="sorting_1">{{$area->id}}</td>
                                    <td><input type="text" class="form-control" style="width: 160px" value="{{$area->name}}" name="name"></td>
                                    <td>
                                        <button style="    float: left; margin-right: 5px;" type="submit" class="btn btn-success js-sweetalert savings" title="edit">save<i class=""></i></button>
                                    </td>
                                    </form>
                                </tr>
                            </tbody>

                        </table>
                    </div></div>
            </div>

        </section>
    </div>
    <!--/. container-fluid -->
    </section>
    <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('javascript')

@stop

resources/views/dashboard/Area/index.blade.php
@extends('layouts.master')
@section('content')
<style>
    #modalLoginForm .modal-header{
        background: #0f3e7c;
        color: white;
    }

    #modalLoginForm .modal-header span{
       color: white;
        position: relative;
        top: -12px;
        right: -3px;
    }

    .modal-footer button{
        background: #0f3e7c;
        color: white;
    }
    .modal-footer button:hover {
        background: #0f3e7c;
    }
    #example1 tbody th{
        background: #0f3e7c;
        color: white;
    }
</style>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <form action="{{route('areas.index')}}" method="get" class="example"  style="margin:auto;max-width:300px;margin-left: 0px;margin-top: -15px;">
                            {{--@csrf--}}

                            <br>
                            <input type="text" placeholder="Search.." name="search"  value="{{ request()->get('search') }}">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>

                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{url('admin/dashboard')}}">Home</a></li>
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol>
                    </div>
            </div>
        </div>

            <div class="col-md-4" style="padding-left: -90px">


            </div>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="box-body">
                    <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap"><div class="row">
                        </div></div></div><div class="row">
                    <div class="col-sm-12">
                        <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">

                            <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                                 aria-hidden="true">

                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header text-center">
                                            <h4 class="modal-title w-100 font-weight-bold">Area Add</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>

                                        </div>


                                        <form action="{{route('areas.store')}}" method="post">
                                            @csrf
                                            <div class="modal-body mx-3">
                                                <div class="md-form mb-3" style="text-align: center;font-size: 15px;">
                                                    <i class="fas fa-area-chart prefix grey-text"></i>
                                                    <label data-error="wrong" data-success="right" for="defaultForm-email">Your Area</label>
                                                    <input type="text" name="name" id="defaultForm-email" class="form-control validate" style="width: 250px;
    display: block;
    margin: 0 auto;" required>
                                                </div>

                                            </div>
                                            <div class="modal-footer d-flex justify-content-center">
                                                <button class="btn btn-default">Submit</button>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>

                            <div class="text-center" style="margin-top: -1px">

                            <a href="" style="float: right;border:none !important;padding: 7px 40px;background: #0f3e7c;color: white;" class="btn btn-outline-success btn-rounded mb-4  " data-toggle="modal" data-target="#modalLoginForm">Create
                                </a>
                            </div>

                            <tr role="row">
                                <th class="sorting_asc  custom-card" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending"
                                    aria-label="Rendering engine: activate to sort column descending" style="width: 213.247px;">#</th>
                                <th class="sorting custom-card" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 262.135px;">Name
                                </th>
                                <th class="sorting  custom-card" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 262.135px;">Action
                                </th>

                            </tr>

                            <tbody>
                            <?php
                            $x=1
                            ?>
                            @foreach( $area as  $areas)
                                <tr role="row" class="odd">
                                    <td class="sorting_1  custom-card">{{$x++}}</td>
                                    <td class=" custom-card">{{$areas->name}}</td>
                                    <td class=" custom-card">
                                        <form action="{{route('areas.edit',$areas->id)}}" method="get">
                                            <button style="    float: left; margin-right: 5px;" type="submit" class="btn btn-info js-sweetalert" title="edit"><i class="fa fa-edit"></i></button>
                                        </form>

                                        <form action="{{route('areas.destroy',$areas->id)}}" method="post">
                                            @method('DELETE')
                                            @csrf
                                            <button  type="submit"  onclick="return confirm('Are you sure')" class="btn btn-warning js-sweetalert" title="Delete"><i class="fa fa-trash-o"></i></button>

                                        </form>

                                    </td>

                                </tr>
                            @endforeach
                            </tbody>

                        </table></div></div>
                {{$area->links()}}

            </div>

        </section>
    </div>
    </section>

    </div>

@endsection

@section('javascript')

@stop